/**
 * Config.json Scene Template Import Engine
 *
 * Converts the config.json tree structure generated by the Adobe Animate export plugin
 * into FunnyAnimationAssistant's flat list of SceneObjects.
 *
 * Coordinate conversion formula (retaining compatibility rules from legacy character import pipeline):
 *   centerX = parentX + (width/2 - localX)
 *   centerY = parentY + (height/2 - localY)
 *
 * When importing full scenes / large-size composites, the caller passes the target viewport; the root composite
 * is uniformly scaled within the viewport to prevent 4K Animate stages from only displaying cropped centers when imported.
 */

import { nanoid } from 'nanoid'

import type {
  ConfigCompositeNode,
  ConfigNode,
  ConfigRoot,
  ConfigSymbolNode,
  ExportFrame,
} from '@/types/configImportTypes'
import type { CompositeObject, SceneObject, SymbolMaterial, SymbolObject } from '@/types/sceneObject'
import { buildFileMap } from '@/utils/fileSystemUtils'
import { generateId } from '@/utils/uuid'

// ===== Types =====

/** Resource validation result (retains compatibility with legacy character import pipeline) */
export interface ConfigResourceValidation {
  valid: boolean
  missingFiles: string[]
  foundFiles: Map<string, FileSystemFileHandle>
  resolvedRelativePaths: Map<string, string>
}

// ===== Version Verification =====

/** Minimum required config.json version */
const MIN_CONFIG_VERSION = '2.0.0'

function normalizeAlpha(value: unknown): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) return 1
  return Math.max(0, Math.min(1, value))
}

/**
 * Parses "verX.Y.Z" version string into numeric tuple
 * @returns [major, minor, patch] or null (when invalid format)
 */
function parseVersionTuple(version: string): [number, number, number] | null {
  const match = /^ver(\d+)\.(\d+)\.(\d+)$/.exec(version)
  if (!match) return null
  return [Number(match[1]), Number(match[2]), Number(match[3])]
}

/**
 * Determines whether version satisfies minimum requirement
 * @param version version field value in config.json (e.g. "ver2.0.0")
 * @param minVersion Minimum version number (without "ver" prefix, e.g. "2.0.0")
 */
export function isVersionSatisfied(version: string, minVersion: string): boolean {
  const current = parseVersionTuple(version)
  const required = parseVersionTuple(`ver${minVersion}`)
  if (!current || !required) return false

  for (let i = 0; i < 3; i++) {
    if (current[i]! > required[i]!) return true
    if (current[i]! < required[i]!) return false
  }
  return true // Identical
}

// ===== Parsing =====

/**
 * Parse and validate config.json
 * @throws Error when format is invalid or version does not meet requirements
 */
export function parseConfigJson(jsonStr: string): ConfigRoot {
  const parsed = JSON.parse(jsonStr) as ConfigRoot

  if (parsed.type !== 'composite') {
    throw new Error('config.json root node must be of type composite')
  }
  if (!Array.isArray(parsed.children)) {
    throw new Error('config.json root node is missing children array')
  }

  // Version verification
  if (!parsed.version) {
    throw new Error('config.json is missing version field, please re-export using the latest plugin version')
  }
  if (!isVersionSatisfied(parsed.version, MIN_CONFIG_VERSION)) {
    throw new Error(
      `config.json version is too low (${parsed.version}), minimum requirement is ver${MIN_CONFIG_VERSION}. Please re-export using the latest plugin version`
    )
  }

  return parsed
}

// ===== Path Collection =====

/**
 * Recursively collects frame paths of all symbol nodes in the tree
 */
export function collectAllFramePaths(config: ConfigRoot): Set<string> {
  const paths = new Set<string>()

  function walk(node: ConfigNode): void {
    if (node.type === 'symbol') {
      for (const frame of node.frames) {
        paths.add(frame.path)
      }
    } else {
      for (const child of node.children) {
        walk(child)
      }
    }
  }

  for (const child of config.children) {
    walk(child)
  }
  return paths
}

// ===== Resource Validation =====

/**
 * Validates resource files referenced in config.json
 * Reuses unified directory scanning + suffix matching strategy
 */
export async function validateConfigResources(
  framePaths: Set<string>,
  directoryHandle: FileSystemDirectoryHandle
): Promise<ConfigResourceValidation> {
  const missingFiles: string[] = []
  const foundFiles = new Map<string, FileSystemFileHandle>()
  const resolvedRelativePaths = new Map<string, string>()

  // Recursively scan directory
  const fileMap = new Map<string, FileSystemFileHandle>()
  await buildFileMap(directoryHandle, '', fileMap)

  // Build lowercase → original path index for direct relative path matching
  const lowerFileMap = new Map<string, { filePath: string; handle: FileSystemFileHandle }>()
  for (const [filePath, handle] of fileMap) {
    lowerFileMap.set(filePath.toLowerCase(), { filePath, handle })
  }

  for (const framePath of framePaths) {
    // Primary strategy: direct relative path matching (ver2.0.0 format)
    const normalizedRelative = framePath.replace(/\\/g, '/').toLowerCase()
    const directMatch = lowerFileMap.get(normalizedRelative)
    if (directMatch) {
      foundFiles.set(framePath, directMatch.handle)
      resolvedRelativePaths.set(framePath, directMatch.filePath)
      continue
    }

    // Fallback strategy: absolute path suffix matching (legacy format compatibility)
    let normalized = framePath.replace(/^file:\/\/\//, '')
    try { normalized = decodeURIComponent(normalized) } catch { /* ignore */ }
    normalized = normalized.replace(/\\/g, '/').toLowerCase()

    let bestMatch: { filePath: string; handle: FileSystemFileHandle } | null = null
    for (const [filePath, handle] of fileMap) {
      const lowerFilePath = filePath.toLowerCase()
      if (
        normalized.endsWith(`/${lowerFilePath}`) ||
        normalized === lowerFilePath
      ) {
        if (!bestMatch || filePath.length > bestMatch.filePath.length) {
          bestMatch = { filePath, handle }
        }
      }
    }

    if (bestMatch) {
      foundFiles.set(framePath, bestMatch.handle)
      resolvedRelativePaths.set(framePath, bestMatch.filePath)
    } else {
      const displayPath = normalized.split('/').slice(-3).join('/')
      missingFiles.push(displayPath)
    }
  }

  return {
    valid: missingFiles.length === 0,
    missingFiles,
    foundFiles,
    resolvedRelativePaths,
  }
}

// ===== Frame → Material Conversion =====

/**
 * Converts frames from config.json into SymbolMaterial[]
 * Grouped by keyframe: single frame → static, multiple frames → animation
 */
async function convertFramesToMaterials(
  frames: ExportFrame[],
  name: string,
  fileHandles: Map<string, FileSystemFileHandle>,
  resolvedRelativePaths: Map<string, string>,
  importDirectoryPath: string
): Promise<SymbolMaterial[]> {
  const materials: SymbolMaterial[] = []

  // Group by keyframe
  const keyframeGroups = new Map<number, ExportFrame[]>()
  for (const frame of frames) {
    const key = frame.keyframe
    if (!keyframeGroups.has(key)) {
      keyframeGroups.set(key, [])
    }
    keyframeGroups.get(key)!.push(frame)
  }

  // Sort by subIndex
  for (const [, groupFrames] of keyframeGroups) {
    groupFrames.sort((a, b) => (a.subIndex ?? 0) - (b.subIndex ?? 0))
  }

  const sortedKeyframes = Array.from(keyframeGroups.keys()).sort((a, b) => a - b)

  for (const keyframe of sortedKeyframes) {
    const groupFrames = keyframeGroups.get(keyframe)!
    const materialId = nanoid()

    if (groupFrames.length === 1) {
      // Single frame → static
      const frame = groupFrames[0]!
      const { url, runtimeUrl } = await resolveFrameUrl(frame.path, fileHandles, resolvedRelativePaths, importDirectoryPath)
      const assetName = frame.label ?? `${name} Frame ${keyframe + 1}`

      const mat: SymbolMaterial & { _runtimeUrl?: string } = {
        id: materialId,
        name: assetName,
        type: 'static',
        url,
        ...(runtimeUrl ? { _runtimeUrl: runtimeUrl } : {}),
      }
      materials.push(mat)
    } else {
      // Multiple frames → animation
      const animFrames: { url: string }[] = []
      let firstName = ''

      for (const frame of groupFrames) {
        const { url } = await resolveFrameUrl(frame.path, fileHandles, resolvedRelativePaths, importDirectoryPath)
        animFrames.push({ url })
        if (!firstName && frame.label) {
          firstName = frame.label
        }
      }

      const assetName = firstName || `${name} Animation ${keyframe + 1}`
      materials.push({
        id: materialId,
        name: assetName,
        type: 'animation',
        frames: animFrames,
        fps: 24,
        loop: true,
      })
    }
  }

  return materials
}

/** Resolves frame path into url (relative path) + runtimeUrl (Blob URL) */
async function resolveFrameUrl(
  framePath: string,
  fileHandles: Map<string, FileSystemFileHandle>,
  resolvedRelativePaths: Map<string, string>,
  importDirectoryPath: string
): Promise<{ url: string; runtimeUrl: string }> {
  const fileHandle = fileHandles.get(framePath)
  let url = ''
  let runtimeUrl = ''

  if (fileHandle) {
    try {
      const file = await fileHandle.getFile()
      runtimeUrl = URL.createObjectURL(file)
      const relativePath = (resolvedRelativePaths.get(framePath) ?? '').replace(/\\/g, '/')
      url = importDirectoryPath
        ? `${importDirectoryPath}/${relativePath}`
        : relativePath
    } catch (e) {
      console.warn('[ConfigImporter] Failed to read file:', framePath, e)
    }
  }

  return { url, runtimeUrl }
}

// ===== Main Conversion =====

/** Intermediate result of internal node conversion */
interface ConvertedNode {
  /** All SceneObjects generated by this node (and its children) (DFS order) */
  objects: SceneObject[]
  /** This node's own root object (used by parent to read position) */
  rootObject: SceneObject
}

interface ConvertFitOptions {
  width: number
  height: number
  padding?: number
}

/**
 * Converts config.json tree into a flat list of SceneObjects
 *
 * @param config Parsed ConfigRoot
 * @param canvasCenterX Canvas center X
 * @param canvasCenterY Canvas center Y
 * @param fileHandles File handles map
 * @param resolvedRelativePaths Relative paths map
 * @param importDirectoryPath Path of import directory relative to project root
 */
export async function convertConfigToSceneObjects(
  config: ConfigRoot,
  canvasCenterX: number,
  canvasCenterY: number,
  fileHandles: Map<string, FileSystemFileHandle>,
  resolvedRelativePaths: Map<string, string>,
  importDirectoryPath: string,
  compositeMode: 'union' | 'entity' = 'union',
  fitTo?: ConvertFitOptions
): Promise<SceneObject[]> {
  if (config.children.length === 0) return []

  // Convert root node as composite as a whole (rather than skipping)
  const result = await convertCompositeNode(config, fileHandles, resolvedRelativePaths, importDirectoryPath, compositeMode)
  const allObjects = result.objects

  // Translate everything to canvas center
  // Only top-level objects (i.e., root composite) need offset; child objects follow using local coordinates
  const topLevelObjects = allObjects.filter(o => !o.parentId)
  if (topLevelObjects.length > 0) {
    let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity
    for (const obj of topLevelObjects) {
      // Use visual bounds: center point ± half width/height (accounting for scale)
      const halfW = (obj.width * Math.abs(obj.scaleX ?? 1)) / 2
      const halfH = (obj.height * Math.abs(obj.scaleY ?? 1)) / 2
      minX = Math.min(minX, obj.x - halfW)
      maxX = Math.max(maxX, obj.x + halfW)
      minY = Math.min(minY, obj.y - halfH)
      maxY = Math.max(maxY, obj.y + halfH)
    }
    const bboxCenterX = (minX + maxX) / 2
    const bboxCenterY = (minY + maxY) / 2
    const offsetX = canvasCenterX - bboxCenterX
    const offsetY = canvasCenterY - bboxCenterY

    for (const obj of topLevelObjects) {
      obj.x += offsetX
      obj.y += offsetY
    }

    if (fitTo && fitTo.width > 0 && fitTo.height > 0) {
      const padding = fitTo.padding ?? 0
      const targetWidth = Math.max(fitTo.width - padding * 2, 1)
      const targetHeight = Math.max(fitTo.height - padding * 2, 1)
      const bboxWidth = maxX - minX
      const bboxHeight = maxY - minY
      if (bboxWidth > targetWidth || bboxHeight > targetHeight) {
        const fitScale = Math.min(targetWidth / bboxWidth, targetHeight / bboxHeight)
        for (const obj of topLevelObjects) {
          obj.scaleX *= fitScale
          obj.scaleY *= fitScale
        }
      }
    }
  }

  return allObjects
}

/**
 * Recursively converts a single node
 */
async function convertNode(
  node: ConfigNode,
  fileHandles: Map<string, FileSystemFileHandle>,
  resolvedRelativePaths: Map<string, string>,
  importDirectoryPath: string,
  compositeMode: 'union' | 'entity'
): Promise<ConvertedNode> {
  if (node.type === 'symbol') {
    return convertSymbolNode(node, fileHandles, resolvedRelativePaths, importDirectoryPath)
  } else {
    return convertCompositeNode(node, fileHandles, resolvedRelativePaths, importDirectoryPath, compositeMode)
  }
}

/**
 * Converts symbol leaf node → SymbolObject
 */
async function convertSymbolNode(
  node: ConfigSymbolNode,
  fileHandles: Map<string, FileSystemFileHandle>,
  resolvedRelativePaths: Map<string, string>,
  importDirectoryPath: string
): Promise<ConvertedNode> {
  const { width, height, registrationPoint, scaleX, scaleY, rotation } = node.instanceTransform
  const { parentX, parentY, localX, localY } = registrationPoint

  // Coordinate conversion: registrationPoint → center coordinates (using legacy import compatibility rules)
  const centerX = parentX + (width / 2 - localX)
  const centerY = parentY + (height / 2 - localY)

  // Frames → Materials
  const materials = await convertFramesToMaterials(
    node.frames, node.name,
    fileHandles, resolvedRelativePaths, importDirectoryPath
  )

  const firstMaterialId = materials[0]?.id

  const obj: SymbolObject = {
    id: generateId('sceneobject'),
    type: 'symbol',
    name: node.name,
    alias: node.name,
    refId: '',
    materials,
    ...(firstMaterialId != null ? { currentMaterialId: firstMaterialId } : {}),
    x: centerX,
    y: centerY,
    width,
    height,
    scaleX,
    scaleY,
    rotation: rotation * Math.PI / 180, // Degrees → Radians
    alpha: normalizeAlpha(node.alpha),
    flipX: false,
    zIndex: 10,
    visible: true,
  }

  return { objects: [obj], rootObject: obj }
}

/**
 * Converts composite container node → CompositeObject + child objects
 */
async function convertCompositeNode(
  node: ConfigCompositeNode,
  fileHandles: Map<string, FileSystemFileHandle>,
  resolvedRelativePaths: Map<string, string>,
  importDirectoryPath: string,
  compositeMode: 'union' | 'entity'
): Promise<ConvertedNode> {
  // 1. Recursively convert all child nodes
  const childResults: ConvertedNode[] = []
  for (const child of node.children) {
    const result = await convertNode(child, fileHandles, resolvedRelativePaths, importDirectoryPath, compositeMode)
    childResults.push(result)
  }

  // If only one child node and no other significance, still create composite to maintain hierarchy

  // 2. Calculate child objects visual bounding box center as composite coordinates
  const childRoots = childResults.map(r => r.rootObject)
  let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity
  for (const child of childRoots) {
    const halfW = (child.width * Math.abs(child.scaleX ?? 1)) / 2
    const halfH = (child.height * Math.abs(child.scaleY ?? 1)) / 2
    minX = Math.min(minX, child.x - halfW)
    maxX = Math.max(maxX, child.x + halfW)
    minY = Math.min(minY, child.y - halfH)
    maxY = Math.max(maxY, child.y + halfH)
  }
  const compositeX = childRoots.length > 0 ? (minX + maxX) / 2 : 0
  const compositeY = childRoots.length > 0 ? (minY + maxY) / 2 : 0

  // 3. Create CompositeObject
  const compositeId = generateId('sceneobject')
  const childIds = childRoots.map(c => c.id)

  const compositeObj: CompositeObject = {
    id: compositeId,
    type: 'composite',
    name: node.name,
    alias: node.name,
    refId: '',
    childIds,
    compositeLocked: true,
    compositeMode,
    x: compositeX,
    y: compositeY,
    width: childRoots.length > 0 ? maxX - minX : 0,
    height: childRoots.length > 0 ? maxY - minY : 0,
    scaleX: 1,
    scaleY: 1,
    rotation: 0,
    alpha: normalizeAlpha(node.alpha),
    flipX: false,
    zIndex: 10,
    visible: true,
  }

  // 4. Convert child coordinates to local coordinates relative to composite center + set parentId
  for (const child of childRoots) {
    child.x -= compositeX
    child.y -= compositeY
    child.parentId = compositeId
  }

  // 5. Assemble flat list (composite first, followed by child objects)
  const allObjects: SceneObject[] = [compositeObj]
  for (const result of childResults) {
    allObjects.push(...result.objects)
  }

  return { objects: allObjects, rootObject: compositeObj }
}
